x-common-variables: &common-variables
  DATABASE_URL: &database-url postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: mooncaketv-postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      <<: *common-variables
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=C --lc-ctype=C"
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - mooncake-web-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mooncaketv -d mooncaketv"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Redis for Caching
  redis:
    image: redis:7-alpine
    container_name: mooncaketv-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 64mb --maxmemory-policy allkeys-lru
    env_file:
      - .env
    deploy:
      resources:
        limits:
          memory: 96M
        reservations:
          memory: 48M
    volumes:
      - ./redis_data:/data
    networks:
      - mooncake-web-network

  # Next.js Application
  mcweb:
    image: ghcr.io/mooncaketv/mooncaketv:latest
    container_name: mooncaketv-web
    restart: unless-stopped
    env_file:
      - .env
    environment:
      <<: *common-variables
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started
    networks:
      - mooncake-web-network

  # Caddy Reverse Proxy
  caddy:
    image: caddy:2.8-alpine
    container_name: mooncaketv-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    env_file:
      - .env
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_data:/data
      - ./caddy_config:/config
    networks:
      - mooncake-web-network
    depends_on:
      - mcweb

  pgweb:
    image: sosedoff/pgweb:latest
    container_name: mooncaketv-pgweb
    restart: unless-stopped
    env_file:
      - .env
    environment:
      <<: *common-variables
      PGWEB_DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
    networks:
      - mooncake-web-network
    depends_on:
      - postgres

networks:
  mooncake-web-network:
    driver: bridge
    name: mooncake-web-network
