x-common-variables: &common-variables
  DATABASE_URL: &database-url postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}

services:
  # Database Migration Service (runs once and exits)
  migrate:
    build:
      context: .
      dockerfile: ./migrate/Dockerfile
    container_name: mooncaketv-migrate
    env_file:
      - .env
    environment:
      <<: *common-variables
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - mooncake-web-network
    restart: "no"

networks:
  mooncake-web-network:
    external: true
    name: mooncake-web-network
